name: Select source

concurrency: 
  group: ai_book
  
on: 
  workflow_dispatch:
    inputs:
      source:
        type: string
        required: true
        description: source id to run the scrapper
      refetch:
        type: boolean

jobs:
  pythonSources:
    name: Handling all the python based sources
    runs-on: ubuntu-latest
    steps:
      - name: checking out the repo
        uses: actions/checkout@v3
      
      - name: setting up python dependecies
        run: pip3 install -r requirements.txt
      
      - name: download database
        env:
          DATABASE_URL: https://raw.githubusercontent.com/${{github.repository}}/db/database.db
        run: |
          if curl -I -s -f $DATABASE_URL -o /dev/null;
            then
              wget $DATABASE_URL
              echo "file downloaded"
            else
              echo "database doesn't exists"
              echo $DATABASE_URL
          fi 
      
      - name: fetching the new resources of the sources
        env:
          REFETCH: 1
        run: python3 -m scrappers.python.${{ inputs.source }}
      
      - name: building json files (resources and sources) from database
        run: python3 build_script.py
        
      - name: clearing all the source code
        run: |
          rm -rf .github/
          rm -rf scrappers/
          rm -rf drafts/
          rm -rf utils/
          rm -rf build_script.py
          rm -rf README.md
          rm -rf requirements.txt
          rm -rf .gitignore
      
      - name: checking modified files
        run: git status


      - name: update the database branch with new resources
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated database of python sources"
          branch: db 
          push_options: '--force'
          create_branch: true
